### PR TITLE
#163549986 Admin can delete political party 

### PR DESCRIPTION
**Pull request by lenileiro**
### What does this PR do?
Admin User should be able to delete individual political party 

### How should this be manually tested?
* Clone the repo by git clone by : https://github.com/lenileiro/politico-api.git

* Navigate into the project by: cd political-api

* activate a virtual environment:
       ```bash
           #!/bin/bash
          $ source venv/bin/activate
      ```

* Install dependencies by: pip install -r requirements.txt
* Run the server by: python run.py
* Hit the following endpoint with postman: http://127.0.0.1:5000/api/v1/parties/1/name ['PATCH']

### Description of Task to be completed?
create rest endpoint where admin user can delete patch request to remove a political party by its ID;

### What are the relevant pivotal tracker stories?
[#163549986](https://www.pivotaltracker.com/story/show/163549986)

### Screenshots
image

image

### CODE REVIEW

**Comment by Nduhiu17** [comment]
Good job. You can return status 204 instead of 200 for delete

**Comment by lenileiro** [comment]
@Nduhiu17 working on that asap. 
could help me with the badges?

**Comment by Nduhiu17** [comment]
Have you already connected with Travis, coveralls and code climate?

**Comment by Nduhiu17** [comment]
Have you already connected with Travis, coveralls and code climate?

**Comment by lenileiro** [comment]
@Nduhiu17 am having troubles with the connection

**Comment by Nduhiu17** [comment]
After connecting you have to create a travis.yml file with the settings to run test for building. Then I coverages are displayed by coveralls. You just pick their badges

**Comment by Nduhiu17** [comment]
Which errors are you getting?

**Comment by lenileiro** [comment]
@Nduhiu17 my badges are not working as seen in the readme file , travis ci and coveralls not building project

**Comment by Nduhiu17** [comment]
Have seen you have a,.travis.yml file... Have you connected your repo to
Travis on their website?

**Pull request merged**
